config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "addresses#index"

  resources :addresses
end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = Address.all
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)

    if @address.save
      redirect_to @address
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])

    if @address.update(address_params)
      redirect_to @address
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def address_params
      params.require(:address).permit(:name, :street, :zip, :city, :phone, :email)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<h1>New Address</h1>

<%= form_with model: @address do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= @address.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :street %><br>
    <%= form.text_field :street %>
    <%= @address.errors.full_messages_for(:street).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :zip %><br>
    <%= form.text_field :zip %>
    <%= @address.errors.full_messages_for(:zip).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
    <%= @address.errors.full_messages_for(:city).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :phone %><br>
    <%= form.text_field :phone %>
    <%= @address.errors.full_messages_for(:phone).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <%= @address.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<%= render "form", address: @address %>

app/views/addresses/index.html.erb
<h1>Hello rails. This is the list of addresses.</h1>

<ul>
  <% @addresses.each do |address| %>
    <li>
      <a href=<%= address_path(address) %>">
      <%= address.name %></a>
    </li>
  <% end %>
</ul>
<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<%= render "form", address: @address %>

app/views/addresses/show.html.erb
<h1><%= @address.name %></h1>
<p><%= @address.street %></p>
<p><%= @address.zip %></p>
<p><%= @address.city %></p>
<p><%= @address.phone %></p>
<p><%= @address.email %></p>

<%= link_to "Edit", edit_address_path(@address) %>
<%= link_to "Delete", address_path(@address), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Addressbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>